author: bel-from-nz
name: Import Env File
description: Imports env vars from file

inputs:
  env-file:
    description: Env file full path
    required: true
    type: string
  env-dir:
    description: Text to echo
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Import environment variables from a file
      id: import-env
      shell: bash
      run: |
        pwd
        ls -l ${{ inputs.env-dir }}
        while read line; do
          echo "$line" >> $GITHUB_ENV
        done < ${{ inputs.env-file }}