author: bel-from-nz
name: Set Terraform Environment variables
description: Set TF Envs

inputs:
  inputs:
    environment:
      description: 'Environment for workflow'
      type: string
      required: true

runs:
  using: composite
  steps:
    - name: Set Terraform Environment variables
      id: run-set-tf-vars
      shell: bash
      run: bash ${{ github.action_path }}/settfenv.sh
      env:
        TF_SUBSCRIPTION_ID: ${{ vars.TF_SUBSCRIPTION_ID || env.TF_SUBSCRIPTION_ID }}
        TF_STATE_RESOURCE_GROUP: ${{ vars.TF_STATE_RESOURCE_GROUP || env.TF_STATE_RESOURCE_GROUP }}
        TF_STATE_BLOB_ACCOUNT: ${{ vars.TF_STATE_BLOB_ACCOUNT || env.TF_STATE_BLOB_ACCOUNT }}
        TF_STATE_BLOB_CONTAINER: ${{ vars.TF_STATE_BLOB_CONTAINER || env.TF_STATE_BLOB_CONTAINER }}
        TF_VAR_FILE: ${{ vars.TF_VAR_FILE || env.TF_VAR_FILE }}
        TF_BLOB_FILE: ${{ vars.TF_BLOB_FILE || env.TF_BLOB_FILE }}
        ARM_CLIENT_ID: "${{ vars.AZURE_CLIENT_ID }}"
        ARM_SUBSCRIPTION_ID: "${{ vars.AZURE_SUBSCRIPTION_ID }}"
        ARM_TENANT_ID: "${{ vars.AZURE_TENANT_ID }}"
        ENVIRONMENT_NAME: ${{ inputs.environment }}