author: bel-from-nz
name: Learning Pathway build
description: node build for Learning pathway tutorial

inputs:
  github-token:
    description: The GitHub token
    required: true
  node-version:
    description: Node JS version
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github-token }}
    - name: use node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: npm install
      shell: bash
      run: npm install
    - name: npm run build
      shell: bash
      run: npm run build
