author: bel-from-nz
name: Echo This
description: test run script

inputs:
  github-token:
    description: The GitHub token
    required: true
  echo-text:
    description: Text to echo
    required: true
    type: string

outputs:
  time: # id of output
    description: 'The time of the command'
    value: ${{ steps.run-echo.outputs.time }}

runs:
  using: composite
  steps:
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github-token }}
    - name: run echo
      id: run-echo
      shell: bash
      run: bash ${{ github.action_path }}/echo.sh '${{ inputs.echo-text }}'