name: build-test-deploy
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run build
        uses: bel-from-nz/actions-learning-pathway/.github/actions/learnbuild@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          node-version: '18.x'
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: run build
        uses: bel-from-nz/actions-learning-pathway/.github/actions/learnbuild@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          node-version: '18.x'
      - run: npm test
  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: run build
        uses: bel-from-nz/actions-learning-pathway/.github/actions/learnbuild@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          node-version: '18.x'

      - name: configure github pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next

      - name: upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./out"

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v1
