name: hello-world
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: true
        default: 'Manual User'

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "Hello ${{ github.event.inputs.name }}"
      - run: echo "$(cat hello_world.txt)"
