name: hello-world
on: workflow_dispatch

permissions:
  contents: read

jobs:
  call-hello-world-job:
    uses: bel-from-nz/actions-learning-pathway/.github/workflows/hello-world-reuse.yml@main
    with:
      env: dev

  call-hello-world-job2:
    uses: bel-from-nz/actions-learning-pathway/.github/workflows/hello-world-reuse.yml@main
    with:
      env: test
      destroyResources: true