name: hello-world-reuse
on:
  workflow_call:
    inputs:
      env:
        description: 'Environment'
        required: true
        type: string
        default: 'dev'

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    env:
      MY_VARIABLE: "hello world (${{ inputs.env }})"

    steps:
      - run: echo "Hello from called workflow ${{ var.TEST_NAME }}"
