name: hello-world-reuse
on:
  workflow_call:
    inputs:
      env:
        description: 'Environment'
        required: true
        type: string
        default: 'dev'
      destroyResources:
        description: 'Destroy resources'
        required: false
        type: boolean
        default: false

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    environment: "hello world (${{ inputs.env }})"

    steps:
      - run: echo "Hello from called workflow ${{ vars.TEST_NAME }}"

  wait-for-destroy-confirm:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: ${{ inputs.destroyResources }}
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: bel-from-nz
          minimum-approvals: 1
          issue-title: "Terraform Destroy has been requested"
          issue-body: |
            Terraform Destroy has been requested.

            Pipeline: ${{ github.workflow }}
            Requested for: ${{ github.actor }}
            Repo: ${{ github.repository }}
          exclude-workflow-initiator-as-approver: false
