name: test-env-file

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for workflow'
        required: true
        type: choice
        options:
          - dev
          - test

jobs:
  getvars:
    runs-on: ubuntu-latest

    env:
      ENV_FILE: "${{ github.workspace }}/workflow_vars/${{ inputs.environment }}-vars.env"  # This is a public environment variable

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Read Vars
        uses: bel-from-nz/actions-learning-pathway/.github/actions/readenv@main
        with:
          env-file: ${{ env.ENV_FILE }}

      - name: Echo environment variable
        run: |
          echo "Runner from var file is ${{ env.RUNNER }}"
          echo "TF State File name from var file is ${{ env.TF_STATE_FILE }}"
