name: test-env-file-template

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment for workflow'
        type: string
        required: true
      run_apply:
        description: 'Run Apply'
        default: false
        type: boolean
      runner:
        description: 'Runner for workflow'
        type: string
        default: ubuntu-latest
        required: true

defaults:
  run:
    shell: bash

env:
  ENV_FILE: "${{ github.workspace }}/workflow_vars/${{ inputs.environment }}-vars.env"

jobs:
  calltestenv:
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.environment }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Read Vars file
        if: ${{ hashFiles(env.ENV_FILE) != ''}}
        uses: bel-from-nz/actions-learning-pathway/.github/actions/readenv@main
        with:
          env-file: ${{ env.ENV_FILE }}

      - name: Set Terraform Env Vars
        uses: bel-from-nz/actions-learning-pathway/.github/actions/set-tf-env@main
        with:
          environment: ${{ inputs.environment }}

      - name: Echo Env Vars
        run: |
          echo "Sub: ${{ env.TF_SUBSCRIPTION_ID }}"
          echo "RG: ${{ env.TF_STATE_RESOURCE_GROUP }}"
          echo "Storage: ${{ env.TF_STATE_BLOB_ACCOUNT }}"
          echo "Container: ${{ env.TF_STATE_BLOB_CONTAINER }}"
          echo "vars: ${{ env.TF_VAR_FILE  }}"
          echo "state: ${{ env.TF_BLOB_FILE }}"
          echo "arm client: ${{ env.ARM_CLIENT_ID }}"
          echo "arm sub: ${{ env.ARM_SUBSCRIPTION_ID }}"
          echo "arm tenant: ${{ env.ARM_TENANT_ID }}"

  runapplytest:
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.environment }}
    if: ${{ inputs.run_apply }}
    steps:
      - name: Echo Env Vars for apply
        run: |
          echo "arm client: ${{ vars.ARM_CLIENT_ID }}"
          echo "arm sub: ${{ vars.ARM_SUBSCRIPTION_ID }}"
          echo "arm tenant: ${{ vars.ARM_TENANT_ID }}"