name: test-env-vars

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for workflow'
        required: true
        type: choice
        options:
          - development
          - test
          - production
      terraform_action:
        description: 'Terraform Action'
        default: apply
        type: choice
        options:
          - apply
          - destroy
          - plan

defaults:
  run:
    shell: bash

run-name: ${{ inputs.terraform_action }} to ${{ inputs.environment }} by @${{ github.actor }} for ${{ github.workflow }}

jobs:
  call-test-sub-id:
    name: "Run sub id test for ${{ inputs.environment }}"
    uses: bel-from-nz/actions-learning-pathway/.github/workflows/test-env-vars-subid-template.yml@main
    with:
      runner: ubuntu-latest

  call-test-env-vars:
    name: "Run Var Test for ${{ inputs.environment }}"
    needs: call-test-sub-id
    uses: bel-from-nz/actions-learning-pathway/.github/workflows/test-env-vars-template.yml@main
    with:
      environment: ${{ inputs.environment }}
      terraform_action: ${{ inputs.terraform_action }}
      runner: ubuntu-latest
      azure_subscription_id: ${{ needs.call-test-sub-id.outputs.azure_subscription_id }}
