name: Test Temp dir
on: workflow_dispatch

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run install
      id: run-install
      uses: ./.github/actions/tfplandoc
