name: Echo Secrets and Variables
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_VARIABLE: "worflowvar"  # This is a public environment variable

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Echo environment variable
      run: echo "My environment variable is $MY_VARIABLE" # This is your variable that will not be masked

    - name: Echo GitHub secret
      run: echo "My GitHub secret is ${{ secrets.MY_GITHUB_SECRET }}" # This is the secret you added in a previous step

  dev:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Echo environment variable
      run: echo "My DEV environment variable is ${{ vars.TEST_ENV_VAR }}"

  prod:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Echo environment variable
      run: echo "My PROD environment variable is ${{ vars.TEST_ENV_VAR }}"

  echo:
    runs-on: ubuntu-latest
    steps:
    - name: run echo
      uses: bel-from-nz/actions-learning-pathway/.github/actions/echothis@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}