name: Echo Secrets and Variables
on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_VARIABLE: "workflow-var"  # This is a public environment variable

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Echo environment variable
      run: echo "My environment variable is $MY_VARIABLE" # This is your variable that will not be masked

    - name: Echo GitHub secret
      run: echo "My GitHub secret is ${{ secrets.MY_GITHUB_SECRET }}" # This is the secret you added in a previous step

  dev:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Echo environment variable
      run: |
        echo "My DEV environment variable is ${{ vars.TEST_ENV_VAR }}"
        echo "My DEV environment variable is $TEST_ENV_VAR"

  test:
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Echo environment variable
      run: |
        echo "My Test environment variable is ${{ vars.TEST_ENV_VAR }}"
        echo "My Test environment variable is $TEST_ENV_VAR"
        echo "TF_SUBSCRIPTION_ID=$TF_SUBSCRIPTION_ID" >> $GITHUB_ENV
        echo "TF_STATE_RESOURCE_GROUP=$TF_STATE_RESOURCE_GROUP" >> $GITHUB_ENV
        if [$TF_STATE_BLOB_ACCOUNT -eq '' ]; then
          echo "TF_STATE_BLOB_ACCOUNT=satftestae01" >> $GITHUB_ENV
        else
          echo "TF_STATE_BLOB_ACCOUNT=$TF_STATE_BLOB_ACCOUNT" >> $GITHUB_ENV
        fi

    - name: Echo environment variable 2
      run: |
        echo ${{ env.TF_SUBSCRIPTION_ID }}
        echo ${{ env.TF_STATE_RESOURCE_GROUP }}
        echo ${{ env.TF_STATE_BLOB_ACCOUNT }}

  prod:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Echo environment variable
      run: echo "My PROD environment variable is ${{ vars.TEST_ENV_VAR }}"

  echo:
    runs-on: ubuntu-latest
    steps:
    - name: run echo
      id: run-echo
      uses: bel-from-nz/actions-learning-pathway/.github/actions/echothis@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        echo-text: "calling from test-secrets:echo step"

    - name: Echo Time Output
      id: echo-time
      run: echo "Time is $TIME"
      shell: bash
      env:
        TIME: ${{ steps.run-echo.outputs.time }}