name: test-env-file

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for workflow'
        required: true
        type: choice
        options:
          - development
          - test
          - production

defaults:
  run:
    shell: bash

env:
  ENV_FILE: "${{ github.workspace }}/workflow_vars/${{ inputs.environment }}-vars.env"

jobs:
  getvars:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Read Vars
        if: ${{ hashFiles(env.ENV_FILE) != ''}}
        uses: bel-from-nz/actions-learning-pathway/.github/actions/readenv@main
        with:
          env-file: ${{ env.ENV_FILE }}

      - name: Echo environment variable
        run: echo "My DEV environment variable is ${{ vars.TEST_ENV_VAR }}"

      - name: Echo Get Vars output
        if: ${{ hashFiles(env.ENV_FILE) != ''}}
        run: |
          echo "Sub: ${{ env.TF_SUBSCRIPTION_ID }}"
          echo "RG: ${{ env.TF_STATE_RESOURCE_GROUP }}"
          echo "Storage: ${{ env.TF_STATE_BLOB_ACCOUNT }}"
          echo "Container: ${{ env.TF_STATE_BLOB_CONTAINER == '' && 'tfstate' || env.TF_STATE_BLOB_CONTAINER }}"
          echo "vars: ${{ env.TF_VAR_FILE }}"
          echo "state: ${{ env.TF_BLOB_FILE  == '' && 'terraform.tfstate' || env.TF_BLOB_FILE }}"

      - name: Echo Get Vars output
        if: ${{ hashFiles(env.ENV_FILE) == ''}}
        run: |
          echo "Sub: ${{ vars.TF_SUBSCRIPTION_ID }}"
          echo "RG: ${{ vars.TF_STATE_RESOURCE_GROUP }}"
          echo "Storage: ${{ vars.TF_STATE_BLOB_ACCOUNT }}"
          echo "Container: ${{ vars.TF_STATE_BLOB_CONTAINER == '' && 'tfstate' || vars.TF_STATE_BLOB_CONTAINER }}"
          echo "vars: ${{ vars.TF_VAR_FILE }}"
          echo "state: ${{ vars.TF_BLOB_FILE  == '' && 'terraform.tfstate' || vars.TF_BLOB_FILE }}"