name: test-env-file

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for workflow'
        required: true
        type: choice
        options:
          - development
          - production

jobs:
  getvars:
    runs-on: ubuntu-latest

    outputs:
      RUNNER: ${{ env.RUNNER == '' && 'ubuntu-latest' || env.RUNNER }}
      TF_STATE_FILE: ${{ env.TF_STATE_FILE == '' && 'default-01.tfstate' || env.TF_STATE_FILE }}
      TF_BLOB_CONTAINER: ${{ env.TF_BLOB_CONTAINER == '' && 'tfstate' || env.TF_BLOB_CONTAINER }}


    env:
      ENV_FILE: "${{ github.workspace }}/workflow_vars/${{ inputs.environment }}-vars.env"  # This is a public environment variable

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Read Vars
        uses: bel-from-nz/actions-learning-pathway/.github/actions/readenv@main
        with:
          env-file: ${{ env.ENV_FILE }}

      - name: Echo environment variable
        run: |
          echo "Runner from var file is ${{ env.RUNNER }}"
          echo "TF State File name from var file is ${{ env.TF_STATE_FILE }}"

  envjob:
    needs: getvars
    runs-on: ${{ needs.getvars.outputs.RUNNER }}
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Echo environment variable
        run: echo "My DEV environment variable is ${{ vars.TEST_ENV_VAR }}"

      - name: Echo environment variable
        run: |
          echo "Runner from var file is ${{ needs.getvars.outputs.RUNNER }}"
          echo "TF State File name from var file is ${{ needs.getvars.outputs.TF_STATE_FILE }}"
          echo "TF Blob container name from var file is ${{ needs.getvars.outputs.TF_BLOB_CONTAINER }}"