name: test-env-file

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for workflow'
        required: true
        type: choice
        options:
          - development
          - test
          - production

defaults:
  run:
    shell: bash

env:
  ENV_FILE: "${{ github.workspace }}/workflow_vars/${{ inputs.environment }}-vars.env"

jobs:
  getvars:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Read Vars
        if: ${{ hashFiles(env.ENV_FILE) != ''}}
        uses: bel-from-nz/actions-learning-pathway/.github/actions/readenv@main
        with:
          env-file: ${{ env.ENV_FILE }}

      - name: Echo environment variable
        run: echo "My environment variable is ${{ vars.TEST_ENV_VAR }}"

      - name: Set Env Vars
        if: ${{ hashFiles(env.ENV_FILE) == ''}}
        run: |
          echo "TF_SUBSCRIPTION_ID=${{ vars.TF_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "TF_STATE_RESOURCE_GROUP=${{ vars.TF_STATE_RESOURCE_GROUP }}" >> $GITHUB_ENV
          echo "TF_STATE_BLOB_ACCOUNT=${{ vars.TF_STATE_BLOB_ACCOUNT }}" >> $GITHUB_ENV
          echo "TF_STATE_BLOB_CONTAINER=${{ vars.TF_STATE_BLOB_CONTAINER }}" >> $GITHUB_ENV
          echo "TF_VAR_FILE=${{ vars.TF_VAR_FILE  }}" >> $GITHUB_ENV
          echo "TF_BLOB_FILE=${{ vars.TF_BLOB_FILE }}" >> $GITHUB_ENV

      - name: Set Env Var defaults
        run: |
          echo "TF_STATE_BLOB_CONTAINER=${{ env.TF_STATE_BLOB_CONTAINER == '' && 'tfstate' || env.TF_STATE_BLOB_CONTAINER }}" >> $GITHUB_ENV
          echo "TF_VAR_FILE=${{ env.TF_VAR_FILE == '' && format( '{0}.tfenv', inputs.environment) || env.TF_VAR_FILE  }}" >> $GITHUB_ENV
          echo "TF_BLOB_FILE=${{ env.TF_BLOB_FILE  == '' && 'terraform.tfstate' || env.TF_BLOB_FILE }}" >> $GITHUB_ENV

      - name: Echo Env Vars
        run: |
          echo "Sub: ${{ env.TF_SUBSCRIPTION_ID }}"
          echo "RG: ${{ env.TF_STATE_RESOURCE_GROUP }}"
          echo "Storage: ${{ env.TF_STATE_BLOB_ACCOUNT }}"
          echo "Container: ${{ env.TF_STATE_BLOB_CONTAINER }}"
          echo "vars: ${{ env.TF_VAR_FILE  }}"
          echo "state: ${{ env.TF_BLOB_FILE }}"
