name: Test TF Vars
on:
  workflow_dispatch:
    inputs:
      tfvars_input:
        description: 'input tfvars'
        type: string
        default: 'name=default'

jobs:
  testvars:
    runs-on: ubuntu-latest
    environment: test_tfvars

    env:
      EXTRA_TF_VARS: ${{ vars.EXTRA_TF_VARS }}
      EXTRA_TF_VARS_STRINGS: ${{ vars.EXTRA_TF_VARS_STRINGS }}


    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: run tfvars 1
      id: run-tf-vars-1
      uses: bel-from-nz/actions-learning-pathway/.github/actions/tfvar@main
      with:
        tfvar-list: ${{ env.EXTRA_TF_VARS }}

    - name: run tfvars 2
      id: run-tf-vars-2
      uses: bel-from-nz/actions-learning-pathway/.github/actions/tfvar@main
      with:
        tfvar-list: ${{ env.EXTRA_TF_VARS_STRINGS }}

    - name: run tfvars 3
      id: run-tf-vars-3
      uses: bel-from-nz/actions-learning-pathway/.github/actions/tfvar@main
      with:
        tfvar-list: ${{ inputs.tfvars_input }}

    - name: Echo vars
      id: echo-vars
      run: |
        echo "testing tfvars - check envs"
