name: test-env-file

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for workflow'
        required: true
        type: choice
        options:
          - development
          - test
          - production
      run_apply:
        description: 'Run Apply'
        default: false
        type: boolean

defaults:
  run:
    shell: bash

env:
  runner: ubuntu-latest

jobs:
  call-test-env-file:
    uses: bel-from-nz/actions-learning-pathway/.github/workflows/test-env-file-template.yml@main
    with:
      environment: ${{ inputs.environment }}
      run_apply: ${{ inputs.run_apply }}
      runner: ubuntu-latest
