name: test-env-file

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for workflow'
        required: true
        type: choice
        options:
          - dev
          - test

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ENV_FILE: "${{ github.workspace }}/worflow_vars/${{ inputs.environment }}-vars.env"  # This is a public environment variable

    steps:
      - name: Read Vars
        uses: bel-from-nz/actions-learning-pathway/.github/actions/readenv@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          env-file: ${{ env.ENV_FILE }}

      - name: Echo environment variable
        run: |
          echo "Runner from var file is ${{ vars.RUNNER }}"
          echo "TF State File name from var file is ${{ vars.TF_STATE_FILE }}"
