name: test-env-obj

on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Environment for workflow'
        required: true
        type: choice
        options:
          - dev
          - test
          - prod

defaults:
  run:
    shell: bash

run-name: Test Env Obj ${{ inputs.target_environment }} by @${{ github.actor }} for ${{ github.workflow }}

env:
  sub_name_dev: "sub-dev-ae-001"
  sub_name_test: "sub-test-ae-001"
  sub_name_prod: "sub-prod-ae-001"
  env_obj: |
    {
      "dev": {"name": "apple","quantity": 1},
      "test": {"name": "orange","quantity": 2},
      "prod": {"name": "pear","quantity": 1}
    }

jobs:
  echo:
    runs-on: ubuntu-latest

    env:
      sub_name_var: ${{ format('sub_name_{0}', inputs.target_environment) }}

    steps:
    - name: Echo environment variable
      run: |
        echo "sub name is ${{ env[env.sub_name_var] }}"

    - name: Echo json
      run: |
        env_object='${{ env.env_obj }}'
        echo $env_object | jq -r '.${{inputs.target_environment}} | .name'
        NAME=$(echo $env_object | jq -r '.${{inputs.target_environment}} | .name')
        echo "FRUIT=$NAME" >> $GITHUB_ENV

    - name: Echo env
      run: |
        echo ${{env.FRUIT}}